config/routes.rb
C2g::Application.routes.draw do

  get "inquiries/new"
  get "inquiries/create"
  get "purchases/index"
  get "purchases/new"
  get "purchases/create"

  devise_for :organizations
  devise_for :individuals

  root 'pages#boxes'

  resources :merchandises do
    resources :purchases, only: [ :new, :create ]
    resources :inquiries
  end

  resources :needs do
    resources :donations
  end

  resources :individuals

  get '/individuals/:id/sale_items',
    to: 'individuals#show',
    as: :individuals_sale_items

  get '/individuals/:id/donations',
    to: 'individuals#show',
    as: :individuals_purchases

  get '/individuals/:id/purchases',
    to: 'individuals#show',
    as: :individuals_donations

  resources :donations
  resources :needs
  
  resources :organizations

  get '/organizations/:id/needs',
    to: 'organizations#show',
    as: :organizations_needs

  get '/organizations/:id/benefits',
    to: 'organizations#show',
    as: :organizations_benefits

  resources :pages

  get "join", to: "pages#join"
  get "about", to: "pages#about"

  namespace :admin do
    resources :individuals
  end

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :donor,
    class_name: 'Individual',
    foreign_key: 'donor_id'

  belongs_to :need

  mount_uploader :pic1, ImageUploader
  mount_uploader :pic2, ImageUploader
  mount_uploader :pic3, ImageUploader
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_individual!
  def index
    @donations = Donation.all
  end

  def new
    @need = Need.find(params[:need_id])
    @need_name = @need_name = @need.organization.name
    @donation = @need.donations.new

  end

  def create
    @need = Need.find(params[:need_id])
    @donation = @need.donations.new(donations_params)
    @donation.status = "pending"
    @donation.donor_id = current_individual.id
    if @donation.save
      redirect_to @donation, notice: "Your donation has been submitted"
      Notifier.offer_sent(@donation).deliver
      Notifier.offer_received(@donation).deliver
    else
      render 'new'
    end
  end

  def show
    @donation = Donation.find(params[:id])
  end

  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy
    redirect_to needs_path
  end


private
  def donations_params
    params.require(:donation).permit(:description, :pic1, :pic2, :pic3)
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/create.html.haml
%h1 Donations#create
%p Find me in app/views/donations/create.html.haml

app/views/donations/index.html.haml
%h2 Display all donation transactions
%table
  %tr
    %th ID
    %th Status
    %th Description
  -@donations.each do |d|
    %tr
      %td= d.id
      %td= d.status
      %td= d.description

app/views/donations/new.html.haml
%h2 Fill out this form and we will notify #{@need_name} of your desire to donate!
= form_for [@need, @donation] do |d|
  = d.label :description
  = d.text_field :description
  %p Upload photo
  = d.file_field :pic1
  %p Upload photo
  = d.file_field :pic2
  %p Upload photo
  = d.file_field :pic3
  = d.submit "Submit", class: "btn"

app/views/donations/show.haml
=row :card do
  / # %h3= @donation.title
  %p= @donation.description
  =row :images do
    =link_to @donation.pic1.url(:full) do
      =image_tag @donation.pic1.url(:medium)
    =link_to @donation.pic2.url(:full) do
      =image_tag @donation.pic2.url(:medium)
    =link_to @donation.pic3.url(:full) do
      =image_tag @donation.pic3.url(:medium)
  =row :buttons do
    =link_to new_need_donation_path(@donation), class: "btn" do
      Donate
    =link_to "Delete Donation", @donation, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn"