config/routes.rb
C2g::Application.routes.draw do

  get "inquiries/new"
  get "inquiries/create"
  get "purchases/index"
  get "purchases/new"
  get "purchases/create"

  devise_for :organizations
  devise_for :individuals

  root 'pages#boxes'

  resources :merchandises do
    resources :purchases, only: [ :new, :create ]
    resources :inquiries
  end

  resources :needs do
    resources :donations
  end

  resources :individuals

  get '/individuals/:id/sale_items',
    to: 'individuals#show',
    as: :individuals_sale_items

  get '/individuals/:id/donations',
    to: 'individuals#show',
    as: :individuals_purchases

  get '/individuals/:id/purchases',
    to: 'individuals#show',
    as: :individuals_donations

  resources :donations
  resources :needs
  
  resources :organizations

  get '/organizations/:id/needs',
    to: 'organizations#show',
    as: :organizations_needs

  get '/organizations/:id/benefits',
    to: 'organizations#show',
    as: :organizations_benefits

  resources :pages

  get "join", to: "pages#join"
  get "about", to: "pages#about"

  namespace :admin do
    resources :individuals
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :needs
  
  has_many :benefits,
    class_name: 'Merchandise',
    foreign_key: 'organization_id'

  #would be good to search all merchandise associated with an organization
  
  include PgSearch
  pg_search_scope :search, against: [:name], 
    using: {tsearch: {dictionary: "english"}}
      # associated_against: {merchandise: [:title, :description]}
  def self.text_search(query)
    if query.present?
      search(query)
    else
      scoped
    end
  end

end

app/controllers/organizations/organizations_controller.rb
class Organizations::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)

    if current_organizaton
      organization_path(current_organization)
    end

  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  layout :determine_layout

  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.find_by id: params[:id]

    # TODO: determine if there's a better way
    @view = @_env['PATH_INFO'].split(/\//)[-1]
    @view = 'needs' if @view =~ /\d+/

    case @view
      when 'needs'
        @needs = @organization.needs
      when 'benefits'
        @benefits = @organization.benefits
      else
        # default   
      end
  end

private

  def determine_layout

    if @organization == current_organization
      'dashboard'
    else
      'application'
    end


  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
    def dashboard_content(view)
    render partial: view
  end

  def organization_show(organization)
    if organization == current_organization
      render partial: 'dashboard'
    else
      render partial: 'profile'
    end
  end
end

app/views/organizations/_benefits.haml
.row
  .columns.large-12
    %h3 Benefits
    %table
      %thead
        %tr
          %th Sale Item
          %th Description
      %tbody
        - @benefits.each do |benefit|
          %tr
            %td= link_to benefit.title, merchandise_path(benefit)
            %td= link_to benefit.description, merchandise_path(benefit)

app/views/organizations/_dashboard.haml
- content_for :sidebar do
  %p Picture
  %p= @organization.name
  %p= @organization.email
  %p
    = link_to 'Needs', organizations_needs_path,
      class: 'btn'
  %p
    = link_to 'Benefits', organizations_benefits_path,
      class: 'btn'

= dashboard_content(@view)

app/views/organizations/_needs.haml
.row
  .columns.large-12
    %h3 Needs
    %table
      %thead
        %tr
          %th need
          %th description
      %tbody
        - @needs.each do |need|
          %tr
            %td= link_to need.title, need_path(need)
            %td= link_to need.description, need_path(need)

app/views/organizations/_profile.haml
= row :card do
  %p Organization Picture
  %h3= @organization.name
  %p= @organization.email

app/views/organizations/show.haml
= organization_show(@organization)