config/routes.rb
C2g::Application.routes.draw do

  get "inquiries/new"
  get "inquiries/create"
  get "purchases/index"
  get "purchases/new"
  get "purchases/create"

  devise_for :organizations
  devise_for :individuals

  root 'pages#boxes'

  resources :merchandises do
    resources :purchases, only: [ :new, :create ]
    resources :inquiries
  end

  resources :needs do
    resources :donations
  end

  resources :individuals

  get '/individuals/:id/sale_items',
    to: 'individuals#show',
    as: :individuals_sale_items

  get '/individuals/:id/donations',
    to: 'individuals#show',
    as: :individuals_purchases

  get '/individuals/:id/purchases',
    to: 'individuals#show',
    as: :individuals_donations

  resources :donations
  resources :needs
  
  resources :organizations

  get '/organizations/:id/needs',
    to: 'organizations#show',
    as: :organizations_needs

  get '/organizations/:id/benefits',
    to: 'organizations#show',
    as: :organizations_benefits

  resources :pages

  get "join", to: "pages#join"
  get "about", to: "pages#about"

  namespace :admin do
    resources :individuals
  end

end

app/views/layouts/partials/_footer.haml
= m :footer do
  = row :nav do
    %nav.columns.small-8.small-centered
      %ul.text-center
        %li
          = link_to 'About', about_path
        %li
          = link_to 'Join', join_path
        %li
          = link_to 'Contact', '#'
        %li
          = link_to 'FAQ', '#'

app/views/layouts/partials/_header.haml
%nav.top-bar
  %ul.title-area
    -# Title Area
    %li.name
      %h1
        =link_to root_path do
          .logo
            =image_tag "horizontal-color-on-transparent.png"

    -# Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    %li.toggle-topbar
      = link_to '#' do
        %span Menu
        %i{ class: 'fa fa-chevron-down' }

  %section.top-bar-section

    -# Right Nav Section
    %ul.right
      -if organization_signed_in?
        %li
          = link_to 'My Account', '#'
        %li
          = link_to 'Edit Profile', edit_organization_registration_path
        %li
          = link_to 'Sign out', destroy_organization_session_path, method: :delete

      -elsif individual_signed_in?
        %li
          = link_to 'My Account', '#'
        %li
          = link_to 'Edit Profile', edit_individual_registration_path
        %li
          = link_to 'Sign out', destroy_individual_session_path, method: :delete

      -else
        %li
          =link_to 'Organization Sign In', new_organization_session_path
        %li
          =link_to 'Individual Sign In', new_individual_session_path
        %li
          =link_to 'Sign up', join_path

app/views/layouts/partials/_layout.haml
- opts    = _opts
- content = _content

%div{ opts }
  = content

app/views/layouts/partials/_merch_search_bar.haml
- placeholder_text = text_placeholder
- opts = _opts

= row :merch_search_bar,
  class: opts[:class],
  id:    opts[:id] do
  = form_tag merchandises_path, method: :get do
    .row.collapse
      .columns.small-10
        = txt_field placeholder_text,
          class: 'text-field-search'
      .columns.small-2
        = button_tag :query, class: "btn btn-search postfix" do
          %icon{ class: 'fa fa-search' }






/ = form_tag merchandises_path, method: :get do
/   .row.collapse
/     .columns.small-10
/       = text_field_tag :query, params[:query], placeholder: "What would you like to buy?", class: "search", autofocus: true
/     .columns.small-2
/       = button_tag :query, class: "btn btn-search postfix" do
/         %icon{ class: 'fa fa-search' }

app/views/layouts/partials/_row.haml
- opts    = _opts
- content = _content

.row{ opts }
  = content

app/views/layouts/partials/_search_bar.haml
- placeholder_text = text_placeholder
- opts = _opts

= row :search_bar,
  class: opts[:class],
  id:    opts[:id] do
  = form_tag needs_path, method: :get do
    .row.collapse
      .columns.small-10
        = txt_field placeholder_text,
          class: 'text-field-search'
      .columns.small-2
        = button_tag :query, class: "btn btn-search postfix" do
          %icon{ class: 'fa fa-search' }

app/views/layouts/partials/_txt_field.haml
- placeholder_text = text_placeholder
- opts = _opts

= text_field_tag :query, params[:query], placeholder: placeholder_text, class: opts[:class], id: opts[:id]